parameters:
#    tahrir_blog.example.class: Tahrir\BlogBundle\Example

services:
#    tahrir_blog.example:
#        class: %tahrir_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
